stage2core=(
COMP20020 "Digital Systems" 5
COMP20070 "Databases and Information Systems I" 5
COMP20110 "Discrete Mathematics for Computer Science" 5
COMP20250 "Introduction to Java" 5
COMP20320 "Computer Networking" 5
COMP20050 "Software Engineering Project 2" 5
COMP20180 "Intro to Operating Systems" 5
COMP20280 "Data Structures" 5
COMP20290 "Algorithms" 5
MST20050 "Linear Algebra II" 5
)

stage2elective=(
MATH10200 "Matrix Algebra" 5
COMP20030 "Web Design" 5
COMP20090 "Introduction to Cognitive Science" 5
COMP20200 "UNIX Programming" 5
)
