stage4core=(
COMP30900 "Final Year Project Foundations" 5
COMP30910 "FYP: Design and Implementation" 10
)

stage4elective=(
COMP30190 "Program Construction II" 5
COMP30220 "Distributed Systems" 5
COMP30230 "Connectionist Computing" 5
COMP30240 "Multi-Agent Systems" 5
COMP30250 "Parallel and Cluster Computing" 5
COMP30520 "Cloud Computing (UG)" 5
COMP30690 "Information Theory" 5
COMP30930 "Optimisation" 5
COMP40370 "Data Mining" 5
COMP47490 "Machine Learning (UG)" 5
SCI30080 "Professional Placement-Science" 5
COMP30110 "Spatial Information Systems" 5
COMP30540 "Game Development" 5
COMP30720 "Ethical Computer Hacking" 5
COMP40010 "Performance of Computer Systems" 5
COMP40020 "Human Language Technologies" 5
COMP40610 "Information Visualisation" 5
COMP40660 "Advances in Wireless Networking" 5
COMP41280 "Introduction to Information Security" 5
COMP41710 "Human Computer Interaction" 5
COMP47390 "Mobile App Dev - Cocoa Touch" 5
COMP47650 "Deep Learning" 5
COMP47660 "Secure Software Engineering" 5
MATH30180 "An Intro to Coding Theory" 5
)
