stage3core=(
COMP30010 "Foundations of Computing" 5
COMP30040 "Networks and Internet Systems" 5
COMP30070 "Object-Oriented Programming" 5
COMP30080 "Computer Systems" 5
COMP30770 "Programming for Big Data" 5
COMP30860 "Web Development" 5
COMP30870 "Graph Algorithms" 5
)

stage3elective=(
COMP30790 "Industry internship" 15
COMP30880 "Software Engineering Project 3" 15
COMP30020 "Computer Graphics I" 5
COMP30030 "Introduction to Artificial Intelligence" 5
COMP30060 "Program Construction I" 5
)
