stage1core=(
COMP10030 "Algorithmic Problem Solving" 5
COMP10040 "Introduction to Computer Architecture" 5
COMP10070 "Formal Foundations" 5
COMP10110 "Computer Programming I" 5
COMP10300 "Functional Programming" 5
COMP10050 "Software Engineering Project 1" 5
COMP10120 "Computer Programming II" 5
MATH10210 "Foundations of Mathematics for Computer Science I" 5
MATH10220 "Foundations of Mathematics for Computer Science II" 5
STAT10430 "Statistics with Python" 5
)

stage1elective=(
MATH00010 "Introduction to Mathematics" 5
MATH10200 "Matrix Algebra" 5
COMP10130 "Computer Science in Practice" 5
)
